# @package _global_

# data 
Dataset: comm20
graph: True
project_name: comm20

data:
  dataset: "comm20"
  image_size: 20
  channels: 1
  random_flip: true  

dataset:
  name: comm20
  remove_h: null
  molecules: False
  spectre: True
  datadir: 'data/comm20/'

  batch_size: 128
  num_workers: 8

# transfer
transfer: False
Dataset_transfer: mnist

final_adaptive: False
adaptive_mean: True
mean_final: torch.zeros([${data.channels}, ${data.image_size}, ${data.image_size}])
var_final: .5 * torch.ones([${data.channels}, ${data.image_size}, ${data.image_size}])
load: False

# device
device: cuda
dataparallel: True
num_workers: 8 
pin_memory: False

log_stride : 10000
gif_stride: 10000
plot_npar: 64

# training
cache_npar: 64
use_prev_net: True
ema: True
ema_rate: 0.99
grad_clipping: True
grad_clip: 0.1
n_ipf_init: 1
batch_size: 64  # must be smaller than the size of datasets
num_iter : 2000
n_ipf: 20
lr: 0.001

# diffusion schedule
num_steps : 50
gamma_max: 0.01
gamma_min: 0.00001
gamma_space: linear
weight_distrib: False
weight_distrib_alpha: 100
fast_sampling: True

# cache
num_cache_batches: 1
cache_refresh_stride: 100

# setting
visualize_loader: False