# @package _global_

# data 
Dataset: sbm
graph: True

data:
  dataset: "sbm"
  channels: 1
  random_flip: true
  min_num_communities: 2
  max_num_communities: 5
  min_community_size: 20
  max_community_size: 40
  intra_prob: 0.005
  inter_prob: 0.3
  image_size: max_community_size*max_num_communities

# transfer
transfer: False
Dataset_transfer: mnist

final_adaptive: False
adaptive_mean: True
mean_final: torch.zeros([${data.channels}, ${data.image_size}, ${data.image_size}])
var_final: .5 * torch.ones([${data.channels}, ${data.image_size}, ${data.image_size}])
load: False

# device
device: cuda
dataparallel: True
num_workers: 8 
pin_memory: False

# logging
# log_stride : 10
log_stride : 5000
gif_stride: 5000
plot_npar: 32

# training
cache_npar: 32
use_prev_net: True
ema: True
ema_rate: 0.999
grad_clipping: True
grad_clip: 1.0
n_ipf_init: 1
batch_size: 32  # must be smaller than the size of datasets
num_iter : 10000
n_ipf: 10
lr: 0.0001

# diffusion schedule
num_steps : 50
gamma_max: 0.1
gamma_min: 0.00001
gamma_space: linear
weight_distrib: False
weight_distrib_alpha: 100
fast_sampling: True

