# @package _global_

# data 
Dataset: sbm
graph: True
project_name: sbm

data:
  dataset: "sbm"
  channels: 1
  random_flip: true
  min_num_communities: 2
  max_num_communities: 5
  min_community_size: 20
  max_community_size: 40
  intra_prob: 0.005
  inter_prob: 0.3
  image_size: max_community_size*max_num_communities


dataset:
  name: sbm
  remove_h: null
  molecules: False
  spectre: True
  datadir: 'data/sbm/'

  batch_size: 128
  num_workers: 8

# transfer
transfer: False
Dataset_transfer: mnist

final_adaptive: False
adaptive_mean: True
mean_final: torch.zeros([${data.channels}, ${data.image_size}, ${data.image_size}])
var_final: .5 * torch.ones([${data.channels}, ${data.image_size}, ${data.image_size}])
load: False

# device
device: cuda
dataparallel: True
num_workers: 8 
pin_memory: False

# logging
# log_stride : 10
log_stride : 20000
gif_stride: 20000
plot_npar: 32

# training
cache_npar: 32
use_prev_net: False
ema: True
ema_rate: 0.999
grad_clipping: True
grad_clip: 1.0
n_ipf_init: 1
batch_size: 32  # must be smaller than the size of datasets
num_iter : 20000
n_ipf: 30
lr: 0.0001

# diffusion schedule
num_steps : 50
gamma_max: 0.1
gamma_min: 0.00001
gamma_space: linspace
weight_distrib: False
weight_distrib_alpha: 100
fast_sampling: True

# cache
num_cache_batches: 1
cache_refresh_stride: 100

model: 
    n_layers: 10
    hidden_dims: {'dx': 256, 'de': 64, 'dy': 256, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128}
    hidden_mlp_dims: { 'X': 128, 'E': 64, 'y': 256}
    # hidden_dims: {'dx': 4, 'de': 4, 'dy': 4, 'n_head': 2, 'dim_ffX': 32, 'dim_ffE': 32, 'dim_ffy': 4}
    # hidden_mlp_dims: { 'X': 4, 'E': 4, 'y': 4}
    sn_hidden_dim: 32
    output_y: False
    dropout: 0.0
    lambda_train: [0, 10]              # X=1, E = lambda[0], y = lambda[1]

    # Model settings
    diffusion_steps: 500
    diffusion_noise_schedule: 'cosine'              # 'cosine', 'polynomial_2'

    extra_features: 'all'        # 'all', 'cycles', or null
    eigenfeatures: True
    edge_features: 'all'          # 'all', 'dist', 'localngbs' or null
    num_eigenvectors: 12       # eigenvectors
    num_eigenvalues: 10      # eigenvalues
    use_charge: False
    num_degree: 10
    dist_feat: True
    positional_encoding: False

    thres: 1.0
