# @package _global_
graph: False

defaults:
  - launcher: local
  - job
  - dataset: 2d #celeba, 2d, stackedmnist
  - model: Basic #Basic, UNET

# data
data_dir: ./data/

# logging
LOGGER: CSV # NEPTUNE, CSV, NONE
CSV_log_dir: ./

cache_gpu: False
num_cache_batches: 1
cache_refresh_stride: 100
plot_level: 1
mean_match: True
paths: 
  experiments_dir_name: experiments
wandb: 'online'             # online | offline | disabled



# settings
seed: 1234
limit_dist: marginal            # uniform | marginal | marginal_tf

# settings for evaluations
final_model_samples_to_generate: 100
final_model_samples_to_save: 30
final_model_chains_to_save: 20
samples_to_generate: 32
samples_to_save: 10
chains_to_save: 5
test: False

# checkpoint
checkpoint_run: False
checkpoint_it: 13
checkpoint_pass: backward
sample_checkpoint_f: ""
sample_checkpoint_b: ""
checkpoint_f: ""
checkpoint_b: ""