# @package _global_
project_name: comm20

defaults:
  - launcher: local
  - job
  - model: gnn
  - sample: sample

# data
virtual_node: False
transfer: False
dataset:
  batch_size: ${batch_size}
  num_workers: 8

  name: "comm20"
  image_size: 20
  channels: 1
  random_flip: true
  datadir: './data/comm20/'

cache_gpu: False
plot_level: 1
mean_match: True
paths: 
  experiments_dir_name: experiments
  name: ${name}
wandb: 'online'             # online | offline | disabled

# settings
seed: 1234

# settings for evaluations
forward_path: null
backward_path: null
final_samples_to_generate: 100
final_samples_to_save: 30
final_chains_to_save: 20
samples_to_generate: 32
samples_to_save: 10
chains_to_save: 1
test: False
save_every_ipf: 5

# checkpoint
checkpoint_run: False
checkpoint_it: 13
checkpoint_pass: backward
sample_checkpoint_f: ""
sample_checkpoint_b: ""
checkpoint_f: ""
checkpoint_b: ""

# cache
num_cache_batches: 1
cache_refresh_stride: 200

# train
batch_size: 32
use_prev_net: True
ema: True
ema_rate: 0.999
grad_clipping: True
grad_clip: 1.0
n_ipf_init: 1
num_iter: 2000
n_ipf: 1000
lr: 0.001
limit_dist: marginal_tf            # uniform | marginal | marginal_tf,  ame with marginal when without transfer data
clean_loss_weight: 0.0001
noise_level: 1.0
reg_weight: 0.0
edge_weight: 1.0
rand_time: False

# diffusion schedule
num_steps : 50
gamma_max: 0.1
gamma_min: 0.00001
gamma_space: linear
weight_distrib: False
weight_distrib_alpha: 100
fast_sampling: True

# device
device: cuda
dataparallel: True
num_workers: 8 
pin_memory: False
log_stride : 20000
gif_stride: 20000


# logging
LOGGER: CSV # NEPTUNE, CSV, NONE
CSV_log_dir: ./
name: default