# @package _global_
graph: False

defaults:
  - launcher: local
  - job
  - dataset: 2d #celeba, 2d, stackedmnist
  - model: Basic #Basic, UNET

# data
data_dir: ./data/

# logging
LOGGER: CSV # NEPTUNE, CSV, NONE
CSV_log_dir: ./

cache_gpu: False
num_cache_batches: 1
cache_refresh_stride: 100
plot_level: 1
mean_match: True
paths: 
  experiments_dir_name: experiments
wandb: 'online'             # online | offline | disabled

# checkpoint
checkpoint_run: False
checkpoint_it: 13
checkpoint_pass: backward
sample_checkpoint_f: ""
sample_checkpoint_b: ""
checkpoint_f: ""
checkpoint_b: ""

# settings
seed: 1234
thres: 1.5
scale: 4
visualize_loader: False